# Generated by Django 4.2.7 on 2023-12-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile', '0003_alter_historicalperformance_vendor'),
        ('purchase_order_tracking', '0006_alter_purchaseorder_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_profile.vendor', to_field='vendor_code'),
        ),
    ]
